# Generated by Django 4.1.3 on 2022-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='13488508087', max_length=11),
        ),
    ]
