# Generated by Django 4.1.3 on 2022-12-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=32, unique=True)),
                ('Name', models.CharField(default=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d', max_length=64)),
                ('Password', models.CharField(max_length=256)),
                ('Authority', models.IntegerField(default=0)),
                ('LocationProvince', models.CharField(max_length=48)),
                ('LocationCity', models.CharField(max_length=48)),
                ('LocationArea', models.CharField(max_length=48)),
            ],
        ),
    ]
